PYTHON_CMD=$1
STATIC_FILE=$2
DYNAMIC_FILE=$3
XYZ_FILE=$4
OVITO_FILE=$5
ANIMATION_FILE=$6
OVITO_GUI_MODE=1 xvfb-run $PYTHON_CMD main.py -s $STATIC_FILE -d $DYNAMIC_FILE --xyz $XYZ_FILE -o $OVITO_FILE -a $ANIMATION_FILE